### PR TITLE
TACO

### PR DESCRIPTION
**Pull request by caykey**
accept

### CODE REVIEW

**Comment by tascord** [comment]
+1

**Review by tascord — APPROVED** [review]
Pog

**Comment by serxka** [comment]
Hello, thank you for contributing! However unfortunately this unacceptably impacts usability and deviates from the project goal. I will be denying this merge request.

**Comment by tascord** [comment]
Hmm,, might wanna reconsider since new rust versions have released. This may greatly increase performance on some architecture. @serxka 

`-- Oscar :)`

**Comment by tascord** [comment]
@serxka

**Comment by tascord** [comment]
@serxka

**Comment by tascord** [comment]
@serxka see above

**Comment by tascord** [comment]
@serxka

**Comment by tascord** [comment]
@serxka

**Comment by tascord** [comment]
@serxka splease

**Comment by tascord** [comment]
@serxka

**Comment by serxka** [comment]
Locking

**Comment by tascord** [comment]
@serxka

**Pull request closed without merging**
